# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
    ]
